<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class AddAdmsPages extends AbstractSeed
{
    /**
     * Cadastra pagina na tabela `adms_pages` se ainda não existirem.
     *
     * Este método é executado para popular a tabela `adms_pages` com registros iniciais dos paginas.
     * Primeiro, verifica se já existe pagina na tabela com base no name. 
     * Se o pagina não existir, os dados são inseridos na tabela.
     * 
     * @return void
     */
    public function run(): void
    {
        // Variável para receber os dados a serem inseridos
        $data = [];

        // Variável para receber os dados que devem ser validados antes de cadastrar
        $pages = [
            // ===== GRUPO 1: DASHBOARD =====
            ['name'=> 'Dashboard', 'controller' => 'Dashboard', 'controller_url' => 'dashboard', 'directory' => 'dashboard', 'obs' => 'Página inicial do administrativo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 1],

            // ===== GRUPO 2: USUÁRIOS =====
            ['name'=> 'Cadastrar Usuário', 'controller' => 'CreateUser', 'controller_url' => 'create-user', 'directory' => 'users', 'obs' => 'Página com o formulário cadastrar usuário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Listar Usuários', 'controller' => 'ListUsers', 'controller_url' => 'list-users', 'directory' => 'users', 'obs' => 'Página para listar o usuários.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Visualizar Usuário', 'controller' => 'ViewUser', 'controller_url' => 'view-user', 'directory' => 'users', 'obs' => 'Página apresentar os detalhes do usuário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Editar Usuário', 'controller' => 'UpdateUser', 'controller_url' => 'update-user', 'directory' => 'users', 'obs' => 'Página com o formulário editar usuário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Editar Imagem do Usuário', 'controller' => 'UpdateUserImage', 'controller_url' => 'update-user-image', 'directory' => 'users', 'obs' => 'Página com o formulário editar imagem do usuário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Editar Senha do Usuário', 'controller' => 'UpdatePasswordUser', 'controller_url' => 'update-password-user', 'directory' => 'users', 'obs' => 'Página com o formulário editar senha do usuário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Apagar Usuário', 'controller' => 'DeleteUser', 'controller_url' => 'delete-user', 'directory' => 'users', 'obs' => 'Página para apagar o usuário do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Troca Obrigatória de Senha', 'controller' => 'ForcePasswordChange', 'controller_url' => 'force-password-change', 'directory' => 'users', 'obs' => 'Página privada para troca obrigatória de senha.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Remover Imagem do Usuário','controller' => 'DeleteUserImage','controller_url' => 'delete-user-image','directory' => 'users','obs' => 'Página para remover a imagem do usuário.','public_page' => 0,'page_status' => 1,'adms_packages_page_id' => 1,'adms_groups_page_id' => 2],
            ['name'=> 'Perfil do Usuário', 'controller' => 'Profile', 'controller_url' => 'profile', 'directory' => 'users', 'obs' => 'Página para visualizar e editar o perfil do usuário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Editar Senha do Usuário via perfil', 'controller' => 'UpdatePassword', 'controller_url' => 'update-password', 'directory' => 'users', 'obs' => 'Página com o formulário editar senha do usuário via perfil.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            ['name'=> 'Importar Usuários', 'controller' => 'ImportUsers', 'controller_url' => 'import-users', 'directory' => 'users', 'obs' => 'Página para importar usuários via CSV.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 2],
            // ===== GRUPO 3: NÍVEIS DE ACESSO =====
            ['name'=> 'Cadastrar Nível de Acesso', 'controller' => 'CreateAccessLevel', 'controller_url' => 'create-access-level', 'directory' => 'accessLevels', 'obs' => 'Página com o formulário cadastrar nível de acesso.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],
            ['name'=> 'Listar Níveis de Acesso', 'controller' => 'ListAccessLevels', 'controller_url' => 'list-access-levels', 'directory' => 'accessLevels', 'obs' => 'Página para listar o níveis de acesso.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],
            ['name'=> 'Visualizar Nível de Acesso', 'controller' => 'ViewAccessLevel', 'controller_url' => 'view-access-level', 'directory' => 'accessLevels', 'obs' => 'Página apresentar os detalhes do nível de acesso.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],
            ['name'=> 'Editar Nível de Acesso', 'controller' => 'UpdateAccessLevel', 'controller_url' => 'update-access-level', 'directory' => 'accessLevels', 'obs' => 'Página com o formulário editar nível de acesso.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],           
            ['name'=> 'Apagar Nível de Acesso', 'controller' => 'DeleteAccessLevel', 'controller_url' => 'delete-access-level', 'directory' => 'accessLevels', 'obs' => 'Página para apagar o nível de acesso do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],
            ['name'=> 'Editar Nível de Acesso do usuário', 'controller' => 'UpdateUserAccessLevels', 'controller_url' => 'update-user-access-levels', 'directory' => 'accessLevels', 'obs' => 'Página para editar o nível de acesso do usuário no banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],
            ['name'=> 'Sincronizar Nível de Acesso', 'controller' => 'AccessLevelPageSync', 'controller_url' => 'access-level-page-sync', 'directory' => 'accessLevels', 'obs' => 'Sincronizar os níveis de acesso com as páginas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],
            ['name'=> 'Importar Níveis de Acesso', 'controller' => 'ImportAccessLevels', 'controller_url' => 'import-access-levels', 'directory' => 'accessLevels', 'obs' => 'Página para importar níveis de acesso via CSV.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 3],

            // ===== GRUPO 4: PACOTES =====
            ['name'=> 'Cadastrar Pacote', 'controller' => 'CreatePackage', 'controller_url' => 'create-package', 'directory' => 'packages', 'obs' => 'Página com o formulário cadastrar pacote.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 4],
            ['name'=> 'Listar Pacotes', 'controller' => 'ListPackages', 'controller_url' => 'list-packages', 'directory' => 'packages', 'obs' => 'Página para listar o pacotes.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 4],
            ['name'=> 'Visualizar Pacote', 'controller' => 'ViewPackage', 'controller_url' => 'view-package', 'directory' => 'packages', 'obs' => 'Página apresentar os detalhes do pacote.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 4],
            ['name'=> 'Editar Pacote', 'controller' => 'UpdatePackage', 'controller_url' => 'update-package', 'directory' => 'packages', 'obs' => 'Página com o formulário editar pacote.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 4],            
            ['name'=> 'Apagar Pacote', 'controller' => 'DeletePackage', 'controller_url' => 'delete-package', 'directory' => 'packages', 'obs' => 'Página para apagar o pacote do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 4],

            // ===== GRUPO 5: GRUPOS DE PÁGINAS =====
            ['name'=> 'Cadastrar Grupo de Página', 'controller' => 'CreateGroupPage', 'controller_url' => 'create-group-page', 'directory' => 'groupsPages', 'obs' => 'Página com o formulário cadastrar grupo de página.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 5],
            ['name'=> 'Listar Grupos de Páginas', 'controller' => 'ListGroupsPages', 'controller_url' => 'list-groups-pages', 'directory' => 'groupsPages', 'obs' => 'Página para listar o grupos de páginas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 5],
            ['name'=> 'Visualizar Grupo de Página', 'controller' => 'ViewGroupPage', 'controller_url' => 'view-group-page', 'directory' => 'groupsPages', 'obs' => 'Página apresentar os detalhes do grupo de página.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 5],
            ['name'=> 'Editar Grupo de Página', 'controller' => 'UpdateGroupPage', 'controller_url' => 'update-group-page', 'directory' => 'groupsPages', 'obs' => 'Página com o formulário editar grupo de página.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 5],            
            ['name'=> 'Apagar Grupo de Página', 'controller' => 'DeleteGroupPage', 'controller_url' => 'delete-group-page', 'directory' => 'groupsPages', 'obs' => 'Página para apagar o grupo de página do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 5],

            // ===== GRUPO 6: PÁGINAS =====
            ['name'=> 'Cadastrar Página', 'controller' => 'CreatePage', 'controller_url' => 'create-page', 'directory' => 'pages', 'obs' => 'Página com o formulário cadastrar página.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 6],
            ['name'=> 'Listar Páginas', 'controller' => 'ListPages', 'controller_url' => 'list-pages', 'directory' => 'pages', 'obs' => 'Página para listar o páginas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 6],
            ['name'=> 'Visualizar Página', 'controller' => 'ViewPage', 'controller_url' => 'view-group-page', 'directory' => 'pages', 'obs' => 'Página apresentar os detalhes do página.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 6],
            ['name'=> 'Editar Página', 'controller' => 'UpdatePage', 'controller_url' => 'update-group-page', 'directory' => 'pages', 'obs' => 'Página com o formulário editar página.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 6],            
            ['name'=> 'Apagar Página', 'controller' => 'DeletePage', 'controller_url' => 'delete-group-page', 'directory' => 'pages', 'obs' => 'Página para apagar o página do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 6],

            // ===== GRUPO 7: LOGIN =====
            ['name'=> 'Página de Login', 'controller' => 'Login', 'controller_url' => 'login', 'directory' => 'login', 'obs' => 'Página com o formulário de login.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 7],
            ['name'=> 'Cadastrar Novo Usuário', 'controller' => 'NewUser', 'controller_url' => 'new-user', 'directory' => 'login', 'obs' => 'Página com o formulário novo usuário na página de login.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 7],
            ['name'=> 'Recuperar Senha', 'controller' => 'ForgotPassword', 'controller_url' => 'forgot-password', 'directory' => 'login', 'obs' => 'Página com o formulário para recuperar a senha.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 7],
            ['name'=> 'Cadastrar Nova Senha', 'controller' => 'ResetPassword', 'controller_url' => 'reset-password', 'directory' => 'login', 'obs' => 'Página com o formulário cadastrar nova senha no login.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 7],
            ['name'=> 'Sair do Administrativo', 'controller' => 'Logout', 'controller_url' => 'logout', 'directory' => 'login', 'obs' => 'Deslogar do sistema administrativo.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 7],
            
            // ===== GRUPO 8: DEPARTAMENTOS =====
            ['name'=> 'Cadastrar Departamento', 'controller' => 'CreateDepartment', 'controller_url' => 'create-department', 'directory' => 'departments', 'obs' => 'Página com o formulário cadastrar Departamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 8],
            ['name'=> 'Listar Departamentos', 'controller' => 'ListDepartments', 'controller_url' => 'list-departments', 'directory' => 'departments', 'obs' => 'Página para listar o Departamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 8],
            ['name'=> 'Visualizar Departamento', 'controller' => 'ViewDepartment', 'controller_url' => 'view-department', 'directory' => 'departments', 'obs' => 'Página apresentar os detalhes do Departamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 8],
            ['name'=> 'Editar Departamento', 'controller' => 'UpdateDepartments', 'controller_url' => 'update-departments', 'directory' => 'departments', 'obs' => 'Página com o formulário editar Departamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 8],           
            ['name'=> 'Apagar Departamento', 'controller' => 'DeleteDepartment', 'controller_url' => 'delete-department', 'directory' => 'departments', 'obs' => 'Página para apagar o Departamento do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 8],
            ['name'=> 'Importar Departamentos', 'controller' => 'ImportDepartments', 'controller_url' => 'import-departments', 'directory' => 'departments', 'obs' => 'Página para importar Departamentos via CSV.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 8],

            // ===== GRUPO 9: ERROS =====
            ['name'=> 'Erro 403', 'controller' => 'Error403', 'controller_url' => 'logout', 'directory' => 'errors', 'obs' => 'Erro que deve apresentado quando não encontrar a página.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 9],

            // ===== GRUPO 10: CARGOS =====
            ['name'=> 'Cadastrar Cargo', 'controller' => 'CreatePosition', 'controller_url' => 'create-position', 'directory' => 'positions', 'obs' => 'Página com o formulário cadastrar Cargo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 10],
            ['name'=> 'Listar Cargos', 'controller' => 'ListPositions', 'controller_url' => 'list-positions', 'directory' => 'positions', 'obs' => 'Página para listar o Cargos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 10],
            ['name'=> 'Visualizar Cargo', 'controller' => 'ViewPosition', 'controller_url' => 'view-position', 'directory' => 'positions', 'obs' => 'Página apresentar os detalhes do Cargo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 10],
            ['name'=> 'Editar Cargo', 'controller' => 'UpdatePosition', 'controller_url' => 'update-positions', 'directory' => 'positions', 'obs' => 'Página com o formulário editar Cargo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 10],           
            ['name'=> 'Apagar Cargo', 'controller' => 'DeletePosition', 'controller_url' => 'delete-position', 'directory' => 'positions', 'obs' => 'Página para apagar o Cargo do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 10],
            ['name'=> 'Importar Cargos', 'controller' => 'ImportPositions', 'controller_url' => 'import-positions', 'directory' => 'positions', 'obs' => 'Página para importar Cargos via CSV.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 10],

            // ===== GRUPO 11: PERMISSÕES =====
            ['name'=> 'Liberar Permissões', 'controller' => 'ListAccessLevelsPermissions', 'controller_url' => 'list-access-levels-permissions', 'directory' => 'permission', 'obs' => 'Página para liberar permissões para o nível de acesso.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 11],

            // ===== GRUPO 12: BANCOS =====
            ['name'=> 'Cadastrar Banco', 'controller' => 'CreateBank', 'controller_url' => 'create-bank', 'directory' => 'banks', 'obs' => 'Página com o formulário cadastrar Banco.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],
            ['name'=> 'Listar Bancos', 'controller' => 'ListBanks', 'controller_url' => 'list-banks', 'directory' => 'banks', 'obs' => 'Página para listar o Bancos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],
            ['name'=> 'Visualizar Banco', 'controller' => 'ViewBank', 'controller_url' => 'view-bank', 'directory' => 'banks', 'obs' => 'Página apresentar os detalhes do Banco.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],
            ['name'=> 'Editar Banco', 'controller' => 'UpdateBank', 'controller_url' => 'update-bank', 'directory' => 'banks', 'obs' => 'Página com o formulário editar Banco.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],           
            ['name'=> 'Apagar Banco', 'controller' => 'DeleteBank', 'controller_url' => 'delete-bank', 'directory' => 'banks', 'obs' => 'Página para apagar o Banco do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],
            ['name'=> 'ListMovBetweenAccounts', 'controller' => 'ListMovBetweenAccounts', 'controller_url' => 'list-mov-between-accounts', 'directory' => 'banks', 'obs' => 'ListMovBetweenAccounts', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],
            ['name'=> 'MovBetweenAccounts', 'controller' => 'MovBetweenAccounts', 'controller_url' => 'mov-between-accounts', 'directory' => 'banks', 'obs' => 'MovBetweenAccounts', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],
            ['name'=> 'Visualizar Transferências entre Contas', 'controller' => 'ViewTransfer', 'controller_url' => 'view-transfer', 'directory' => 'banks', 'obs' => 'Visualizar Transferências entre Contas', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],
            ['name'=> 'UpdateMovBetweenAccounts', 'controller' => 'UpdateMovBetweenAccounts', 'controller_url' => 'update-mov-between-accounts', 'directory' => 'banks', 'obs' => 'UpdateMovBetweenAccounts', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 12],

            // ===== GRUPO 13: CONTAS À PAGAR =====
            ['name'=> 'Cadastrar Contas à Pagar', 'controller' => 'CreatePay', 'controller_url' => 'create-pay', 'directory' => 'pay', 'obs' => 'Página com o formulário cadastrar Contas à Pagar.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],
            ['name'=> 'Listar Contas à Pagar', 'controller' => 'ListPayments', 'controller_url' => 'list-payments', 'directory' => 'pay', 'obs' => 'Página para listar o Contas à Pagar.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],
            ['name'=> 'Listar Pagamentos de uma Conta', 'controller' => 'ListPartialValues', 'controller_url' => 'list-partial-values', 'directory' => 'pay', 'obs' => 'Página para listar pagamentos parciais de uma Conta.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],
            ['name'=> 'Visualizar Contas à Pagar', 'controller' => 'ViewPay', 'controller_url' => 'view-pay', 'directory' => 'pay', 'obs' => 'Página apresentar os detalhes do Contas à Pagar.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],
            ['name'=> 'Editar Contas à Pagar', 'controller' => 'UpdatePay', 'controller_url' => 'update-pay', 'directory' => 'pay', 'obs' => 'Página com o formulário editar Contas à Pagar.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],           
            ['name'=> 'Apagar Contas à Pagar', 'controller' => 'DeletePay', 'controller_url' => 'delete-pay', 'directory' => 'pay', 'obs' => 'Página para apagar o Contas à Pagar do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],
            ['name'=> 'Parcelar Contas à Pagar', 'controller' => 'Installments', 'controller_url' => 'installments', 'directory' => 'pay', 'obs' => 'Página com o formulário parcelar Conta à Pagar.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],           
            ['name'=> 'Pagar Conta', 'controller' => 'Payment', 'controller_url' => 'payment', 'directory' => 'pay', 'obs' => 'Página para pagar/baixar Conta do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],
            ['name'=> 'Processar o arquivo de importação de pagamentos', 'controller' => 'ProcessFilePayments', 'controller_url' => 'process-file-payments', 'directory' => 'pay', 'obs' => 'Pagina para processar o arquivo de importaçãode pagamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],           
            ['name'=> 'Obter o status das Contas à Pagar', 'controller' => 'GetPaymentsStatus', 'controller_url' => 'get-payments-status', 'directory' => 'pay', 'obs' => 'Página para obter o status dos Contas à Pagar.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],
            ['name'=> 'Verificar se a Conta à Pagar está ocupada', 'controller' => 'CheckBusy', 'controller_url' => 'check-busy', 'directory' => 'pay', 'obs' => 'Página para verificar se a Conta à Pagar está ocupada.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],           
            ['name'=> 'Desocupar a Conta à Pagar ocupada', 'controller' => 'ClearBusyPay', 'controller_url' => 'clear-busy-pay', 'directory' => 'pay', 'obs' => 'Página para Desocupar Conta à Pagar ocupada.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 13],

            // ===== GRUPO 14: CONTAS À RECEBER =====
            ['name'=> 'Cadastrar Contas à Receber', 'controller' => 'CreateReceive', 'controller_url' => 'create-receive', 'directory' => 'receive', 'obs' => 'Página com o formulário cadastrar Contas à Receber.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],
            ['name'=> 'Listar Contas à Receber', 'controller' => 'ListReceipts', 'controller_url' => 'list-receipts', 'directory' => 'receive', 'obs' => 'Página para listar o Contas à Receber.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],
            ['name'=> 'Visualizar Contas à Receber', 'controller' => 'ViewReceive', 'controller_url' => 'view-receive', 'directory' => 'receive', 'obs' => 'Página apresentar os detalhes do Contas à Receber.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],
            ['name'=> 'Editar Contas à Receber', 'controller' => 'UpdateReceive', 'controller_url' => 'update-receive', 'directory' => 'receive', 'obs' => 'Página com o formulário editar Contas à Receber.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],           
            ['name'=> 'Apagar Contas à Receber', 'controller' => 'DeleteReceive', 'controller_url' => 'delete-receive', 'directory' => 'receive', 'obs' => 'Página para apagar o Contas à Receber do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],
            ['name'=> 'Parcelar Contas à Receber', 'controller' => 'InstallmentsReceive', 'controller_url' => 'installments-receive', 'directory' => 'receive', 'obs' => 'Página com o formulário parcelar Conta à Receber.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],          
            ['name'=> 'Receber Conta', 'controller' => 'Receive', 'controller_url' => 'receive', 'directory' => 'receive', 'obs' => 'Página para receber/baixar Conta do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],
            ['name'=> 'Processar o arquivo de importação de Contas à Receber', 'controller' => 'ProcessFileReceipts', 'controller_url' => 'process-file-receipts', 'directory' => 'receive', 'obs' => 'Pagina para processar o arquivo de importação de de Contas à Receber.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],        
            ['name'=> 'Obter o status das Contas a Receber', 'controller' => 'GetReceiptsStatus', 'controller_url' => 'get-receipts-status', 'directory' => 'receive', 'obs' => 'Página para obter o status das Contas à Receber.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],
            ['name'=> 'Verificar se a Conta à Receber está ocupada', 'controller' => 'CheckBusyReceive', 'controller_url' => 'check-busy-receive', 'directory' => 'receive', 'obs' => 'Página para verificar se a Conta à Receber está ocupada.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],          
            ['name'=> 'Desocupar a Conta à Receber ocupada', 'controller' => 'CheckBusyReceive', 'controller_url' => 'clear-busy-receive', 'directory' => 'receive', 'obs' => 'Página para limpar o pagamento ocupado.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 14],
         
            // ===== GRUPO 15: CENTROS DE CUSTO =====
            ['name'=> 'Cadastrar Centros de Custo', 'controller' => 'CreateCostCenter', 'controller_url' => 'create-cost-center', 'directory' => 'costCenter', 'obs' => 'Página com o formulário cadastrar Centros de Custo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 15],
            ['name'=> 'Listar Centros de Custo', 'controller' => 'ListCostCenters', 'controller_url' => 'list-cost-centers', 'directory' => 'costCenter', 'obs' => 'Página para listar o Centros de Custo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 15],
            ['name'=> 'Visualizar Centros de Custo', 'controller' => 'ViewCostCenter', 'controller_url' => 'view-cost-center', 'directory' => 'costCenter', 'obs' => 'Página apresentar os detalhes do Centros de Custo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 15],
            ['name'=> 'Editar Centros de Custo', 'controller' => 'UpdateCostCenter', 'controller_url' => 'update-cost-center', 'directory' => 'costCenter', 'obs' => 'Página com o formulário editar Centros de Custo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 15],           
            ['name'=> 'Apagar Centros de Custo', 'controller' => 'DeleteCostCenter', 'controller_url' => 'delete-cost-center', 'directory' => 'costCenter', 'obs' => 'Página para apagar o Centros de Custo do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 15],
            ['name'=> 'Importar Centros de Custo', 'controller' => 'ImportCostCenters', 'controller_url' => 'import-cost-centers', 'directory' => 'costCenter', 'obs' => 'Página para importar Centros de Custo via CSV.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 15],

            // ===== GRUPO 16: PLANOS DE CONTAS =====
            ['name'=> 'Cadastrar Plano de Contas', 'controller' => 'CreateAccountPlan', 'controller_url' => 'create-account-plan', 'directory' => 'accountsPlan', 'obs' => 'Página com o formulário cadastrar Plano de Contas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 16],
            ['name'=> 'Listar Plano de Contas', 'controller' => 'ListAccountsPlan', 'controller_url' => 'list-accounts-plan', 'directory' => 'accountsPlan', 'obs' => 'Página para listar o Plano de Contas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 16],
            ['name'=> 'Visualizar Plano de Contas', 'controller' => 'ViewAccountPlan', 'controller_url' => 'view-account-plan', 'directory' => 'accountsPlan', 'obs' => 'Página apresentar os detalhes do Plano de Contas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 16],
            ['name'=> 'Editar Plano de Contas', 'controller' => 'UpdateAccountPlan', 'controller_url' => 'update-account-plan', 'directory' => 'accountsPlan', 'obs' => 'Página com o formulário editar Plano de Contas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 16],           
            ['name'=> 'Apagar Plano de Contas', 'controller' => 'DeleteAccountPlan', 'controller_url' => 'delete-account-plan', 'directory' => 'accountsPlan', 'obs' => 'Página para apagar o Plano de Contas do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 16],
           
            // ===== GRUPO 17: FREQUÊNCIAS PARA PAGAMENTO =====
            ['name'=> 'Cadastrar Frequência para Pagamento', 'controller' => 'CreateFrequency', 'controller_url' => 'create-frequency', 'directory' => 'frequency', 'obs' => 'Página com o formulário cadastrar Plano de Contas.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 17],
            ['name'=> 'Listar Frequências para Pagamentos', 'controller' => 'ListFrequencies', 'controller_url' => 'list-frequencies', 'directory' => 'frequency', 'obs' => 'Página para listar o Frequências para Pagamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 17],
            ['name'=> 'Visualizar Frequência para Pagamento', 'controller' => 'ViewFrequency', 'controller_url' => 'view-frequency', 'directory' => 'frequency', 'obs' => 'Página apresentar os detalhes do Frequências para Pagamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 17],
            ['name'=> 'Editar Frequência para Pagamento', 'controller' => 'UpdateFrequency', 'controller_url' => 'update-frequency', 'directory' => 'frequency', 'obs' => 'Página com o formulário editar Frequências para Pagamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 17],           
            ['name'=> 'Apagar Frequência para Pagamento', 'controller' => 'DeleteFrequency', 'controller_url' => 'delete-frequency', 'directory' => 'frequency', 'obs' => 'Página para apagar o Frequências para Pagamentos do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 17],

            // ===== GRUPO 18: CLIENTES =====
            ['name'=> 'Cadastrar Cliente', 'controller' => 'CreateCustomer', 'controller_url' => 'create-customer', 'directory' => 'customer', 'obs' => 'Página com o formulário cadastrar Clientes.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 18],
            ['name'=> 'Listar Clientes', 'controller' => 'ListCustomers', 'controller_url' => 'list-customers', 'directory' => 'customer', 'obs' => 'Página para listar o Clientes.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 18],
            ['name'=> 'Visualizar Cliente', 'controller' => 'ViewCustomer', 'controller_url' => 'view-customer', 'directory' => 'customer', 'obs' => 'Página apresentar os detalhes do Cliente.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 18],
            ['name'=> 'Editar Cliente', 'controller' => 'UpdateCustomer', 'controller_url' => 'update-customer', 'directory' => 'customer', 'obs' => 'Página com o formulário editar Cliente.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 18],           
            ['name'=> 'Apagar Cliente', 'controller' => 'DeleteCustomer', 'controller_url' => 'delete-customer', 'directory' => 'customer', 'obs' => 'Página para apagar o Cliente do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 18],

            // ===== GRUPO 19: FORNECEDORES =====
            ['name'=> 'Cadastrar Fornecedor', 'controller' => 'CreateSupplier', 'controller_url' => 'create-supplier', 'directory' => 'supplier', 'obs' => 'Página com o formulário cadastrar Fornecedor.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 19],
            ['name'=> 'Listar Fornecedores', 'controller' => 'ListSuppliers', 'controller_url' => 'list-suppliers', 'directory' => 'supplier', 'obs' => 'Página para listar o Fornecedores.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 19],
            ['name'=> 'Visualizar Fornecedor', 'controller' => 'ViewSupplier', 'controller_url' => 'view-supplier', 'directory' => 'supplier', 'obs' => 'Página apresentar os detalhes do Fornecedor.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 19],
            ['name'=> 'Editar Fornecedor', 'controller' => 'UpdateSupplier', 'controller_url' => 'update-supplier', 'directory' => 'supplier', 'obs' => 'Página com o formulário editar Fornecedor.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 19],           
            ['name'=> 'Apagar Fornecedor', 'controller' => 'DeleteSupplier', 'controller_url' => 'delete-supplier', 'directory' => 'supplier', 'obs' => 'Página para apagar o Fornecedor do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 19],
            ['name'=> 'Importar Fornecedor', 'controller' => 'ProcessFile', 'controller_url' => 'process-file', 'directory' => 'supplier', 'obs' => 'Página para importar o Fornecedor.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 19],

            // ===== GRUPO 20: FORMAS DE PAGAMENTO =====
            ['name'=> 'Cadastrar Forma de Pagamento', 'controller' => 'CreatePaymentMethod', 'controller_url' => 'create-payment-method', 'directory' => 'paymentMethod', 'obs' => 'Página com o formulário cadastrar Forma de Pagamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 20],
            ['name'=> 'Listar Formas de Pagamento', 'controller' => 'ListPaymentMethods', 'controller_url' => 'list-payment-methods', 'directory' => 'paymentMethod', 'obs' => 'Página para listar o Formas de Pagamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 20],
            ['name'=> 'Visualizar Forma de Pagamento', 'controller' => 'ViewPaymentMethod', 'controller_url' => 'view-payment-method', 'directory' => 'paymentMethod', 'obs' => 'Página apresentar os detalhes do Forma de Pagamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 20],
            ['name'=> 'Editar Forma de Pagamento', 'controller' => 'UpdatePaymentMethod', 'controller_url' => 'update-payment-method', 'directory' => 'paymentMethod', 'obs' => 'Página com o formulário editar Forma de Pagamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 20],           
            ['name'=> 'Apagar Forma de Pagamento', 'controller' => 'DeletePaymentMethod', 'controller_url' => 'delete-payment-method', 'directory' => 'paymentMethod', 'obs' => 'Página para apagar o Forma de Pagamento do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 20],

            // ===== GRUPO 21: RELATÓRIOS FINANCEIROS =====
            ['name'=> 'Listar Movimentos', 'controller' => 'Movements', 'controller_url' => 'movements', 'directory' => 'financialReports', 'obs' => 'Página listar os Movimentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 21],
            ['name'=> 'Listar Fluxo de Caixa', 'controller' => 'CashFlow', 'controller_url' => 'cash-flow', 'directory' => 'financialReports', 'obs' => 'Página para listar o Fluxo de Caixa.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 21],
            ['name'=> 'Exportar o Fluxo de Caixa em PDF', 'controller' => 'ExportPdfCashFlow', 'controller_url' => 'export-pdf-cash-flow', 'directory' => 'financialReports', 'obs' => 'Página para exportar o Fluxo de Caixa em PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 21],
            ['name'=> 'Pagina Resumo Por Centro de Custo', 'controller' => 'CostCenterSummary', 'controller_url' => 'cost-center-summary', 'directory' => 'financialReports', 'obs' => 'Pagina Resumo Por Centro de Custo', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 21],
            ['name'=> 'Pagina Resumo Financeiro Regime de Caixa e Competência', 'controller' => 'FlowCashCompetence', 'controller_url' => 'flow-cash-competence', 'directory' => 'financialReports', 'obs' => 'Pagina Resumo Financeiro Regime de Caixa e Competência', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 21],
    
            // ===== GRUPO 22: MOVIMENTOS =====
            ['name'=> 'Editar Movimentos', 'controller' => 'EditMovement', 'controller_url' => 'edit-movement', 'directory' => 'movement', 'obs' => 'Página para editar o Movimento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 22],
            ['name'=> 'Deletar Movimentos', 'controller' => 'DeleteMovement', 'controller_url' => 'delete-movement', 'directory' => 'movement', 'obs' => 'Página para apagar o Movimento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 22],
            ['name'=> 'Editar Movimento Recebido', 'controller' => 'EditMovementReceive', 'controller_url' => 'edit-movement-receive', 'directory' => 'movement', 'obs' => 'Editar Movimento Recebido', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 22],
            ['name'=> 'Deletar Movimento Recebido', 'controller' => 'DeleteMovementReceive', 'controller_url' => 'delete-movement-receive', 'directory' => 'movement', 'obs' => 'Deletar Movimento Recebido', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 22],
            
            // ===== GRUPO 23: DOCUMENTOS =====
            ['name'=> 'Página para listar Documentos', 'controller' => 'ListDocuments', 'controller_url' => 'list-documents', 'directory' => 'documents', 'obs' => 'Página para listar Documentos', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 23],
            ['name'=> 'Página para cadastrar Documentos', 'controller' => 'CreateDocument', 'controller_url' => 'create-document', 'directory' => 'documents', 'obs' => 'Página para cadastrar Documentos', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 23],
            ['name'=> 'Pagina para visualizar o cadastro do documento', 'controller' => 'ViewDocument', 'controller_url' => 'view-document', 'directory' => 'documents', 'obs' => 'Pagina para visualizar o cadastro do documento', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 23],
            ['name'=> 'Pagina listar Documentos VS Cargos', 'controller' => 'ListDocumentPositions', 'controller_url' => 'list-document-positions', 'directory' => 'documents', 'obs' => 'Pagina listar Documentos VS Cargos', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 23],
            
            // ===== GRUPO 24: TREINAMENTOS =====
            ['name'=> 'Cadastrar Treinamento', 'controller' => 'CreateTraining', 'controller_url' => 'create-training', 'directory' => 'trainings', 'obs' => 'Páginas com o formulário cadastrar Treinamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Listar Treinamentos', 'controller' => 'ListTrainings', 'controller_url' => 'list-trainings', 'directory' => 'trainings', 'obs' => 'Página para listar os Treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Editar Treinamento', 'controller' => 'UpdateTraining', 'controller_url' => 'update-training', 'directory' => 'trainings', 'obs' => 'Página com o formulário editar Treinamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Apagar Treinamento', 'controller' => 'DeleteTraining', 'controller_url' => 'delete-training', 'directory' => 'trainings', 'obs' => 'Página para apagar o Treinamento do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Vincular Cargos a Treinamento', 'controller' => 'TrainingPositions', 'controller_url' => 'training-positions', 'directory' => 'trainings', 'obs' => 'Página para vincular cargos a treinamento.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Agendar Treinamento', 'controller' => 'ScheduleTraining', 'controller_url' => 'schedule-training', 'directory' => 'trainings', 'obs' => 'Página para agendar treinamentos para usuários.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Aplicar Treinamento', 'controller' => 'ApplyTraining', 'controller_url' => 'apply-training', 'directory' => 'trainings', 'obs' => 'Página para registrar a aplicação de treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Histórico de Treinamentos', 'controller' => 'ViewTrainingHistory', 'controller_url' => 'training-history', 'directory' => 'trainings', 'obs' => 'Página para visualizar o histórico de aplicações/agendamentos de treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Matriz por Colaborador', 'controller' => 'MatrixByUser', 'controller_url' => 'matrix-by-user', 'directory' => 'trainings', 'obs' => 'Matriz de treinamentos obrigatórios por colaborador', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Histórico de Reciclagem', 'controller' => 'TrainingHistory', 'controller_url' => 'training-history', 'directory' => 'trainings', 'obs' => 'Histórico detalhado de aplicações/reciclagens', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Status dos Treinamentos', 'controller' => 'ListTrainingStatus', 'controller_url' => 'list-training-status', 'directory' => 'trainings', 'obs' => 'Página para visualizar o status dos treinamentos dos colaboradores.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Matriz de Treinamentos', 'controller' => 'TrainingMatrixManager', 'controller_url' => 'training-matrix-manager', 'directory' => 'trainings', 'obs' => 'Página para gerenciar a matriz de treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Teste de Notificações de Treinamentos', 'controller' => 'TestNotification', 'controller_url' => 'test-notification', 'directory' => 'trainings', 'obs' => 'Página para testar o envio de notificações de treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Atualizar Matriz de Treinamentos', 'controller' => 'UpdateTrainingMatrix', 'controller_url' => 'update-training-matrix', 'directory' => 'trainings', 'obs' => 'Página para atualizar a matriz de treinamentos obrigatórios.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Enviar Notificações de Treinamentos', 'controller' => 'SendNotification', 'controller_url' => 'send-notification', 'directory' => 'trainings', 'obs' => 'Página para enviar notificações de treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name' => 'Vincular Colaboradores ao Treinamento', 'controller' => 'LinkTrainingUsers', 'controller_url' => 'link-training-users', 'directory' => 'trainings','obs' => 'Página para vincular múltiplos colaboradores a um treinamento.','public_page' => 0,'page_status' => 1,'adms_packages_page_id' => 1,'adms_groups_page_id' => 24],
            ['name' => 'Salvar Vínculo de Colaborador','controller' => 'SaveTrainingUserLink','controller_url' => 'save-training-user-link','directory' => 'trainings','obs' => 'Página para salvar vínculo de colaborador ao treinamento.','public_page' => 0, 'page_status' => 1,'adms_packages_page_id' => 1,'adms_groups_page_id' => 24],
            ['name' => 'Remover Vínculo de Colaborador','controller' => 'DeleteTrainingUserLink','controller_url' => 'delete-training-user-link','directory' => 'trainings','obs' => 'Página para remover vínculo individual de colaborador ao treinamento.','public_page' => 0, 'page_status' => 1,'adms_packages_page_id' => 1,'adms_groups_page_id' => 24],
            ['name' => 'Dashboard de KPIs - Treinamentos', 'controller' => 'TrainingKPIDashboard', 'controller_url' => 'training-kpi-dashboard', 'directory' => 'trainings', 'obs' => 'Dashboard com gráficos e indicadores de treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            // ===== GRUPO 24: MATRIZ DE TREINAMENTOS =====
            ['name'=> 'Matriz de Treinamentos Realizados', 'controller' => 'CompletedTrainingsMatrix', 'controller_url' => 'completed-trainings-matrix', 'directory' => 'trainings', 'obs' => 'Matriz de treinamentos realizados por colaborador', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Minhas Avaliações', 'controller' => 'MyEvaluations', 'controller_url' => 'my-evaluations', 'directory' => 'evaluations', 'obs' => 'Página para o colaborador responder avaliações/questionários.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Responder Avaliação', 'controller' => 'ResponderAvaliacao', 'controller_url' => 'responder-avaliacao', 'directory' => 'evaluations', 'obs' => 'Página para o colaborador responder uma avaliação/questionário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Histórico de Avaliações', 'controller' => 'HistoricoAvaliacoes', 'controller_url' => 'historico-avaliacoes', 'directory' => 'evaluations', 'obs' => 'Página para o colaborador consultar avaliações/questionários já respondidos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Notificações', 'controller' => 'Notificacoes', 'controller_url' => 'notificacoes', 'directory' => 'notifications', 'obs' => 'Central de notificações do colaborador.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            ['name'=> 'Visualizar Treinamento','controller' => 'ViewTraining','controller_url' => 'view-training','directory' => 'trainings', 'obs' => 'Página para visualizar os detalhes do treinamento.','public_page' => 0,'page_status' => 1,'adms_packages_page_id' => 1, 'adms_groups_page_id' => 24],
            // ===== GRUPO 25: AVALIAÇÕES =====
            ['name'=> 'Listar Modelos de Avaliação', 'controller' => 'ListEvaluationModels', 'controller_url' => 'list-evaluation-models', 'directory' => 'evaluations', 'obs' => 'Página para listar os modelos de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Cadastrar Modelo de Avaliação', 'controller' => 'CreateEvaluationModel', 'controller_url' => 'create-evaluation-model', 'directory' => 'evaluations', 'obs' => 'Página com o formulário cadastrar modelo de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Visualizar Modelo de Avaliação', 'controller' => 'ViewEvaluationModel', 'controller_url' => 'view-evaluation-model', 'directory' => 'evaluations', 'obs' => 'Página para visualizar detalhes do modelo de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Editar Modelo de Avaliação', 'controller' => 'UpdateEvaluationModel', 'controller_url' => 'update-evaluation-model', 'directory' => 'evaluations', 'obs' => 'Página com o formulário editar modelo de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Apagar Modelo de Avaliação', 'controller' => 'DeleteEvaluationModel', 'controller_url' => 'delete-evaluation-model', 'directory' => 'evaluations', 'obs' => 'Página para apagar modelo de avaliação do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Listar Perguntas de Avaliação', 'controller' => 'ListEvaluationQuestions', 'controller_url' => 'list-evaluation-questions', 'directory' => 'evaluations', 'obs' => 'Página para listar as perguntas de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Cadastrar Pergunta de Avaliação', 'controller' => 'CreateEvaluationQuestion', 'controller_url' => 'create-evaluation-question', 'directory' => 'evaluations', 'obs' => 'Página com o formulário cadastrar pergunta de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Editar Pergunta de Avaliação', 'controller' => 'UpdateEvaluationQuestion', 'controller_url' => 'update-evaluation-question', 'directory' => 'evaluations', 'obs' => 'Página com o formulário editar pergunta de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Apagar Pergunta de Avaliação', 'controller' => 'DeleteEvaluationQuestion', 'controller_url' => 'delete-evaluation-question', 'directory' => 'evaluations', 'obs' => 'Página para apagar pergunta de avaliação do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Aplicar Avaliação', 'controller' => 'ApplyEvaluation', 'controller_url' => 'apply-evaluation', 'directory' => 'evaluations', 'obs' => 'Página para aplicar avaliação ao usuário.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Visualizar Resultado de Avaliação', 'controller' => 'ViewEvaluationResult', 'controller_url' => 'view-evaluation-result', 'directory' => 'evaluations', 'obs' => 'Página para visualizar resultado de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Listar Respostas de Avaliação', 'controller' => 'ListEvaluationAnswers', 'controller_url' => 'list-evaluation-answers', 'directory' => 'evaluations', 'obs' => 'Página para listar respostas de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Cadastrar Resposta de Avaliação', 'controller' => 'CreateEvaluationAnswer', 'controller_url' => 'create-evaluation-answer', 'directory' => 'evaluations', 'obs' => 'Página com o formulário cadastrar resposta de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Editar Resposta de Avaliação', 'controller' => 'UpdateEvaluationAnswer', 'controller_url' => 'update-evaluation-answer', 'directory' => 'evaluations', 'obs' => 'Página com o formulário editar resposta de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Apagar Resposta de Avaliação', 'controller' => 'DeleteEvaluationAnswer', 'controller_url' => 'delete-evaluation-answer', 'directory' => 'evaluations', 'obs' => 'Página para apagar resposta de avaliação do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Visualizar Resposta de Avaliação', 'controller' => 'ViewEvaluationAnswer', 'controller_url' => 'view-evaluation-answer', 'directory' => 'evaluations', 'obs' => 'Página para visualizar detalhes da resposta de avaliação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],
            ['name'=> 'Buscar Perguntas por Modelo', 'controller' => 'GetQuestionsByModel', 'controller_url' => 'get-questions-by-model', 'directory' => 'evaluations', 'obs' => 'Página para buscar perguntas por modelo via AJAX.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 25],

            // ===== GRUPO 26: CONFIGURAÇÕES =====
            ['name'=> 'Configuração de E-mail', 'controller' => 'EmailConfig', 'controller_url' => 'email-config', 'directory' => 'settings', 'obs' => 'Página para configurar servidor de e-mail SMTP.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Cadastrar Configuração de E-mail', 'controller' => 'CreateEmailConfig', 'controller_url' => 'create-email-config', 'directory' => 'settings', 'obs' => 'Salvar configuração SMTP.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Listar Configuração de E-mail', 'controller' => 'ListEmailConfig', 'controller_url' => 'list-email-config', 'directory' => 'settings', 'obs' => 'Exibir configuração SMTP.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Testar Configuração de E-mail', 'controller' => 'TestEmailConfig', 'controller_url' => 'test-email-config', 'directory' => 'settings', 'obs' => 'Testar envio SMTP.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Política de Senha', 'controller' => 'PasswordPolicy', 'controller_url' => 'password-policy', 'directory' => 'settings', 'obs' => 'Configuração da política de senha do sistema.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Ajax Política de Senha', 'controller' => 'AjaxPasswordPolicy', 'controller_url' => 'ajax-password-policy', 'directory' => 'settings', 'obs' => 'Endpoint AJAX para validação de senha da política de senha.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Ajax Validação Simples de Senha', 'controller' => 'AjaxSimplePasswordValidate', 'controller_url' => 'ajax-simple-password-validate', 'directory' => 'settings', 'obs' => 'Endpoint AJAX simples para validação de senha.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            
            // ===== GRUPO 26: CONFIGURAÇÕES - FILIAIS =====
            ['name'=> 'Cadastrar Filial', 'controller' => 'CreateBranch', 'controller_url' => 'create-branch', 'directory' => 'branches', 'obs' => 'Página com o formulário cadastrar Filial.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Listar Filiais', 'controller' => 'ListBranches', 'controller_url' => 'list-branches', 'directory' => 'branches', 'obs' => 'Página para listar as Filiais.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Visualizar Filial', 'controller' => 'ViewBranch', 'controller_url' => 'view-branch', 'directory' => 'branches', 'obs' => 'Página para visualizar os detalhes da Filial.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Editar Filial', 'controller' => 'UpdateBranch', 'controller_url' => 'update-branch', 'directory' => 'branches', 'obs' => 'Página com o formulário editar Filial.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            ['name'=> 'Apagar Filial', 'controller' => 'DeleteBranch', 'controller_url' => 'delete-branch', 'directory' => 'branches', 'obs' => 'Página para apagar a Filial do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 26],
            
            // ===== GRUPO 28: LOGS =====
            ['name' => 'ListLogAlteracoes', 'controller' => 'ListLogAlteracoes','controller_url' => 'list-log-alteracoes', 'directory' => 'logs', 'obs' => 'Listagem de logs de alterações','public_page' => 0, 'page_status' => 1,'adms_packages_page_id' => 1,'adms_groups_page_id' => 28],
            ['name' => 'ViewLogAlteracao', 'controller' => 'ViewLogAlteracao','controller_url' => 'view-log-alteracao', 'directory' => 'logs', 'obs' => 'Detalhamento de log de alteração','public_page' => 0, 'page_status' => 1,'adms_packages_page_id' => 1,'adms_groups_page_id' => 28],
            ['name'=> 'Log de Alterações', 'controller' => 'ListLogAlteracoes', 'controller_url' => 'list-log-alteracoes', 'directory' => 'logs', 'obs' => 'Página para listar logs de alterações do sistema.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 28],
            ['name'=> 'Exportar Logs CSV', 'controller' => 'ExportLogCsv', 'controller_url' => 'export-log-csv', 'directory' => 'logs', 'obs' => 'Página para exportar logs de alterações em CSV.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 28],
            ['name'=> 'Exportar Logs Excel', 'controller' => 'ExportLogExcel', 'controller_url' => 'export-log-excel', 'directory' => 'logs', 'obs' => 'Página para exportar logs de alterações em Excel.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 28],
            ['name'=> 'Exportar Logs PDF', 'controller' => 'ExportLogPdf', 'controller_url' => 'export-log-pdf', 'directory' => 'logs', 'obs' => 'Página para exportar logs de alterações em PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 28],
            ['name'=> 'ListLogAcessos', 'controller' => 'ListLogAcessos', 'controller_url' => 'list-log-acessos', 'directory' => 'logs', 'obs' => 'Página para listar logs de acesso (login/logout).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 28],
            ['name'=> 'Exportar Logs de Acesso Excel', 'controller' => 'ExportLogAcessosExcel', 'controller_url' => 'export-log-acessos-excel', 'directory' => 'logs', 'obs' => 'Exportação dos logs de acesso em Excel.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 28],
            ['name'=> 'Exportar Logs de Acesso PDF', 'controller' => 'ExportLogAcessosPdf', 'controller_url' => 'export-log-acessos-pdf', 'directory' => 'logs', 'obs' => 'Exportação dos logs de acesso em PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 28],
            // ===== GRUPO 29: PLANEJAMENTO ESTRATÉGICO =====
            ['name'=> 'Listar Planos Estratégicos', 'controller' => 'ListStrategicPlans', 'controller_url' => 'list-strategic-plans', 'directory' => 'strategicPlans', 'obs' => 'Página para listar os Planos Estratégicos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 29],
            ['name'=> 'Cadastrar Plano Estratégico', 'controller' => 'CreateStrategicPlan', 'controller_url' => 'create-strategic-plan', 'directory' => 'strategicPlans', 'obs' => 'Página com o formulário cadastrar Plano Estratégico.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 29],
            ['name'=> 'Editar Plano Estratégico', 'controller' => 'EditStrategicPlan', 'controller_url' => 'edit-strategic-plan', 'directory' => 'strategicPlans', 'obs' => 'Página com o formulário editar Plano Estratégico.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 29],
            ['name'=> 'Listar Indicadores Estratégicos', 'controller' => 'StrategicIndicatorsList', 'controller_url' => 'strategic-indicators-list', 'directory' => 'strategicIndicators', 'obs' => 'Página para listar os Indicadores Estratégicos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 29],
            ['name'=> 'Cadastrar Indicador Estratégico', 'controller' => 'StrategicIndicatorsCreate', 'controller_url' => 'strategic-indicators-create', 'directory' => 'strategicIndicators', 'obs' => 'Página com o formulário cadastrar Indicador Estratégico.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 29],
            ['name'=> 'Editar Indicador Estratégico', 'controller' => 'StrategicIndicatorsEdit', 'controller_url' => 'strategic-indicators-edit', 'directory' => 'strategicIndicators', 'obs' => 'Página com o formulário editar Indicador Estratégico.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 29],

            // ===== GRUPO 30: INFORMATIVOS =====
            ['name'=> 'Listar Informativos', 'controller' => 'ListInformativos', 'controller_url' => 'list-informativos', 'directory' => 'informativos', 'obs' => 'Página para listar os informativos da empresa.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            ['name'=> 'Cadastrar Informativo', 'controller' => 'CreateInformativo', 'controller_url' => 'create-informativo', 'directory' => 'informativos', 'obs' => 'Página com o formulário cadastrar informativo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            ['name'=> 'Visualizar Informativo', 'controller' => 'ViewInformativo', 'controller_url' => 'view-informativo', 'directory' => 'informativos', 'obs' => 'Página para visualizar os detalhes do informativo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            ['name'=> 'Editar Informativo', 'controller' => 'UpdateInformativo', 'controller_url' => 'update-informativo', 'directory' => 'informativos', 'obs' => 'Página com o formulário editar informativo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            ['name'=> 'Apagar Informativo', 'controller' => 'DeleteInformativo', 'controller_url' => 'delete-informativo', 'directory' => 'informativos', 'obs' => 'Página para apagar o informativo do banco de dados.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            ['name'=> 'Servir Arquivo de Upload', 'controller' => 'ServeFile', 'controller_url' => 'serve-file', 'directory' => 'serveFile', 'obs' => 'Página para servir arquivos de upload (imagens/anexos) dos informativos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            ['name'=> 'Remover Imagem do Informativo', 'controller' => 'RemoveInformativoImagem', 'controller_url' => 'remove-informativo-imagem', 'directory' => 'informativos', 'obs' => 'Página para remover a imagem do informativo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            ['name'=> 'Remover Anexo do Informativo', 'controller' => 'RemoveInformativoAnexo', 'controller_url' => 'remove-informativo-anexo', 'directory' => 'informativos', 'obs' => 'Página para remover o anexo do informativo.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 30],
            // ===== GRUPO 31: LGPD =====
            ['name'=> 'Listar ROPA', 'controller' => 'LgpdRopa', 'controller_url' => 'lgpd-ropa', 'directory' => 'lgpd', 'obs' => 'Página para listar registros ROPA.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar ROPA', 'controller' => 'LgpdRopaCreate', 'controller_url' => 'lgpd-ropa-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar registro ROPA.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar ROPA', 'controller' => 'LgpdRopaEdit', 'controller_url' => 'lgpd-ropa-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar registro ROPA.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar ROPA', 'controller' => 'LgpdRopaView', 'controller_url' => 'lgpd-ropa-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar registro ROPA.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir ROPA', 'controller' => 'LgpdRopaDelete', 'controller_url' => 'lgpd-ropa-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir registro ROPA.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Listar Categorias de Titulares', 'controller' => 'LgpdCategoriasTitulares', 'controller_url' => 'lgpd-categorias-titulares', 'directory' => 'lgpd', 'obs' => 'Página para listar categorias de titulares LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Categoria de Titular', 'controller' => 'LgpdCategoriasTitularesCreate', 'controller_url' => 'lgpd-categorias-titulares-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar categoria de titular LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Categoria de Titular', 'controller' => 'LgpdCategoriasTitularesEdit', 'controller_url' => 'lgpd-categorias-titulares-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar categoria de titular LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Categoria de Titular', 'controller' => 'LgpdCategoriasTitularesView', 'controller_url' => 'lgpd-categorias-titulares-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar categoria de titular LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Categoria de Titular', 'controller' => 'LgpdCategoriasTitularesDelete', 'controller_url' => 'lgpd-categorias-titulares-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir categoria de titular LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Listar Finalidades', 'controller' => 'LgpdFinalidades', 'controller_url' => 'lgpd-finalidades', 'directory' => 'lgpd', 'obs' => 'Página para listar finalidades LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Finalidade', 'controller' => 'LgpdFinalidadesCreate', 'controller_url' => 'lgpd-finalidades-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar finalidade LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Finalidade', 'controller' => 'LgpdFinalidadesEdit', 'controller_url' => 'lgpd-finalidades-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar finalidade LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Finalidade', 'controller' => 'LgpdFinalidadesView', 'controller_url' => 'lgpd-finalidades-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar finalidade LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Finalidade', 'controller' => 'LgpdFinalidadesDelete', 'controller_url' => 'lgpd-finalidades-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir finalidade LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Listar Bases Legais', 'controller' => 'LgpdBasesLegais', 'controller_url' => 'lgpd-bases-legais', 'directory' => 'lgpd', 'obs' => 'Página para listar bases legais LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Base Legal', 'controller' => 'LgpdBasesLegaisCreate', 'controller_url' => 'lgpd-bases-legais-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar base legal LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Base Legal', 'controller' => 'LgpdBasesLegaisEdit', 'controller_url' => 'lgpd-bases-legais-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar base legal LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Base Legal', 'controller' => 'LgpdBasesLegaisView', 'controller_url' => 'lgpd-bases-legais-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar base legal LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Base Legal', 'controller' => 'LgpdBasesLegaisDelete', 'controller_url' => 'lgpd-bases-legais-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir base legal LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Listar Tipos de Dados', 'controller' => 'LgpdTiposDados', 'controller_url' => 'lgpd-tipos-dados', 'directory' => 'lgpd', 'obs' => 'Página para listar tipos de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Tipo de Dados', 'controller' => 'LgpdTiposDadosCreate', 'controller_url' => 'lgpd-tipos-dados-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar tipo de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Tipo de Dados', 'controller' => 'LgpdTiposDadosEdit', 'controller_url' => 'lgpd-tipos-dados-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar tipo de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Tipo de Dados', 'controller' => 'LgpdTiposDadosView', 'controller_url' => 'lgpd-tipos-dados-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar tipo de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Tipo de Dados', 'controller' => 'LgpdTiposDadosDelete', 'controller_url' => 'lgpd-tipos-dados-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir tipo de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Listar Classificações de Dados', 'controller' => 'LgpdClassificacoesDados', 'controller_url' => 'lgpd-classificacoes-dados', 'directory' => 'lgpd', 'obs' => 'Página para listar classificações de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Classificação de Dados', 'controller' => 'LgpdClassificacoesDadosCreate', 'controller_url' => 'lgpd-classificacoes-dados-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar classificação de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Classificação de Dados', 'controller' => 'LgpdClassificacoesDadosEdit', 'controller_url' => 'lgpd-classificacoes-dados-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar classificação de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Classificação de Dados', 'controller' => 'LgpdClassificacoesDadosView', 'controller_url' => 'lgpd-classificacoes-dados-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar classificação de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Classificação de Dados', 'controller' => 'LgpdClassificacoesDadosDelete', 'controller_url' => 'lgpd-classificacoes-dados-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir classificação de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - INVENTÁRIO =====
            ['name'=> 'Listar Inventário LGPD', 'controller' => 'LgpdInventory', 'controller_url' => 'lgpd-inventory', 'directory' => 'lgpd', 'obs' => 'Página para listar inventário de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Inventário LGPD', 'controller' => 'LgpdInventoryCreate', 'controller_url' => 'lgpd-inventory-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar item do inventário LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Inventário LGPD', 'controller' => 'LgpdInventoryEdit', 'controller_url' => 'lgpd-inventory-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar item do inventário LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Inventário LGPD', 'controller' => 'LgpdInventoryView', 'controller_url' => 'lgpd-inventory-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar item do inventário LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Inventário LGPD', 'controller' => 'LgpdInventoryDelete', 'controller_url' => 'lgpd-inventory-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir item do inventário LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - DATA MAPPING =====
            ['name'=> 'Listar Data Mapping LGPD', 'controller' => 'LgpdDataMapping', 'controller_url' => 'lgpd-data-mapping', 'directory' => 'lgpd', 'obs' => 'Página para listar mapeamento de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Data Mapping LGPD', 'controller' => 'LgpdDataMappingCreate', 'controller_url' => 'lgpd-data-mapping-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar mapeamento de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Data Mapping LGPD', 'controller' => 'LgpdDataMappingEdit', 'controller_url' => 'lgpd-data-mapping-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar mapeamento de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Data Mapping LGPD', 'controller' => 'LgpdDataMappingView', 'controller_url' => 'lgpd-data-mapping-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar mapeamento de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Data Mapping LGPD', 'controller' => 'LgpdDataMappingDelete', 'controller_url' => 'lgpd-data-mapping-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir mapeamento de dados LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - INTEGRAÇÕES =====
            ['name'=> 'Criar ROPA a partir do Inventário', 'controller' => 'LgpdRopaCreateFromInventory', 'controller_url' => 'lgpd-ropa-create-from-inventory', 'directory' => 'lgpd', 'obs' => 'Página para criar ROPA automaticamente a partir do inventário LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Criar Data Mapping a partir da ROPA', 'controller' => 'LgpdDataMappingCreateFromRopa', 'controller_url' => 'lgpd-data-mapping-create-from-ropa', 'directory' => 'lgpd', 'obs' => 'Página para criar Data Mapping automaticamente a partir da ROPA.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Relatório Integrado do Fluxo LGPD', 'controller' => 'LgpdWorkflowReport', 'controller_url' => 'lgpd-workflow-report', 'directory' => 'lgpd', 'obs' => 'Página para visualizar relatório integrado do fluxo completo LGPD (Inventário → ROPA → Data Mapping).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - AIPD =====
            ['name'=> 'Listar AIPD', 'controller' => 'LgpdAipd', 'controller_url' => 'lgpd-aipd', 'directory' => 'lgpd', 'obs' => 'Página para listar Avaliações de Impacto à Proteção de Dados (AIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar AIPD', 'controller' => 'LgpdAipdCreate', 'controller_url' => 'lgpd-aipd-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar Avaliação de Impacto à Proteção de Dados (AIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar AIPD', 'controller' => 'LgpdAipdEdit', 'controller_url' => 'lgpd-aipd-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar Avaliação de Impacto à Proteção de Dados (AIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar AIPD', 'controller' => 'LgpdAipdView', 'controller_url' => 'lgpd-aipd-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar Avaliação de Impacto à Proteção de Dados (AIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir AIPD', 'controller' => 'LgpdAipdDelete', 'controller_url' => 'lgpd-aipd-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir Avaliação de Impacto à Proteção de Dados (AIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Sugestões de AIPD', 'controller' => 'LgpdAipdSuggest', 'controller_url' => 'lgpd-aipd-suggest', 'directory' => 'lgpd', 'obs' => 'Página para visualizar sugestões automáticas de AIPD baseadas na análise dos ROPAs.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - TEMPLATES AIPD =====
            ['name'=> 'Template AIPD - Setor de Saúde', 'controller' => 'LgpdAipdTemplateSaude', 'controller_url' => 'lgpd-aipd-template-saude', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para organizações do setor de saúde.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template AIPD - Setor Financeiro', 'controller' => 'LgpdAipdTemplateFinanceiro', 'controller_url' => 'lgpd-aipd-template-financeiro', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para organizações do setor financeiro.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template AIPD - E-commerce', 'controller' => 'LgpdAipdTemplateEcommerce', 'controller_url' => 'lgpd-aipd-template-ecommerce', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para organizações de e-commerce e vendas online.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template AIPD - Educação', 'controller' => 'LgpdAipdTemplateEducacao', 'controller_url' => 'lgpd-aipd-template-educacao', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para organizações educacionais e treinamentos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template AIPD - RH', 'controller' => 'LgpdAipdTemplateRh', 'controller_url' => 'lgpd-aipd-template-rh', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para Recursos Humanos e gestão de funcionários.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template AIPD - Marketing', 'controller' => 'LgpdAipdTemplateMarketing', 'controller_url' => 'lgpd-aipd-template-marketing', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para marketing e publicidade.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
        ['name'=> 'Template AIPD - Telecomunicações', 'controller' => 'LgpdAipdTemplateTelecom', 'controller_url' => 'lgpd-aipd-template-telecom', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para organizações de telecomunicações.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
        ['name'=> 'Template AIPD - Logística', 'controller' => 'LgpdAipdTemplateLogistica', 'controller_url' => 'lgpd-aipd-template-logistica', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para organizações de logística e transporte.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
        ['name'=> 'Template AIPD - Jurídico', 'controller' => 'LgpdAipdTemplateJuridico', 'controller_url' => 'lgpd-aipd-template-juridico', 'directory' => 'lgpd', 'obs' => 'Template específico de AIPD para organizações jurídicas e advocatícias.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - CONSENTIMENTOS =====
            ['name'=> 'Listar Consentimentos LGPD', 'controller' => 'LgpdConsentimentos', 'controller_url' => 'lgpd-consentimentos', 'directory' => 'lgpd', 'obs' => 'Página para listar consentimentos LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Consentimento LGPD', 'controller' => 'LgpdConsentimentosCreate', 'controller_url' => 'lgpd-consentimentos-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar consentimento LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Consentimento LGPD', 'controller' => 'LgpdConsentimentosEdit', 'controller_url' => 'lgpd-consentimentos-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar consentimento LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Consentimento LGPD', 'controller' => 'LgpdConsentimentosView', 'controller_url' => 'lgpd-consentimentos-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar consentimento LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Consentimento LGPD', 'controller' => 'LgpdConsentimentosDelete', 'controller_url' => 'lgpd-consentimentos-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir consentimento LGPD.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - COLETA DE CONSENTIMENTOS =====
            ['name'=> 'Coleta de Consentimento LGPD', 'controller' => 'LgpdConsentimentoColeta', 'controller_url' => 'lgpd-consentimento-coleta', 'directory' => 'lgpd', 'obs' => 'Página pública para coleta de consentimentos LGPD.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Processar Coleta de Consentimento LGPD', 'controller' => 'LgpdConsentimentoColetaProcessar', 'controller_url' => 'lgpd-consentimento-coleta-processar', 'directory' => 'lgpd', 'obs' => 'Processamento do formulário de coleta de consentimentos LGPD.', 'public_page' => 1, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Enviar Consentimento por E-mail', 'controller' => 'LgpdConsentimentoEmail', 'controller_url' => 'lgpd-consentimento-email', 'directory' => 'lgpd', 'obs' => 'Página para envio de formulário de consentimento por e-mail.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Processar Envio de Consentimento por E-mail', 'controller' => 'LgpdConsentimentoEmailProcessar', 'controller_url' => 'lgpd-consentimento-email-processar', 'directory' => 'lgpd', 'obs' => 'Página para processamento do envio de formulário de consentimento por e-mail.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - TIA =====
            ['name'=> 'Listar Testes TIA', 'controller' => 'LgpdTia', 'controller_url' => 'lgpd-tia', 'directory' => 'lgpd', 'obs' => 'Página para listar Testes de Impacto às Atividades (TIA).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Cadastrar Teste TIA', 'controller' => 'LgpdTiaCreate', 'controller_url' => 'lgpd-tia-create', 'directory' => 'lgpd', 'obs' => 'Página para cadastrar Teste de Impacto às Atividades (TIA).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar Teste TIA', 'controller' => 'LgpdTiaEdit', 'controller_url' => 'lgpd-tia-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar Teste de Impacto às Atividades (TIA).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar Teste TIA', 'controller' => 'LgpdTiaView', 'controller_url' => 'lgpd-tia-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar Teste de Impacto às Atividades (TIA).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir Teste TIA', 'controller' => 'LgpdTiaDelete', 'controller_url' => 'lgpd-tia-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir Teste de Impacto às Atividades (TIA).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - TIA - MELHORIAS =====
            ['name'=> 'Dashboard TIA', 'controller' => 'LgpdTiaDashboard', 'controller_url' => 'lgpd-tia-dashboard', 'directory' => 'lgpd', 'obs' => 'Dashboard com estatísticas e métricas dos testes TIA.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Templates de TIA', 'controller' => 'LgpdTiaTemplates', 'controller_url' => 'lgpd-tia-templates', 'directory' => 'lgpd', 'obs' => 'Página para seleção de templates de TIA por setor.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template TIA - RH', 'controller' => 'LgpdTiaTemplateRh', 'controller_url' => 'lgpd-tia-template-rh', 'directory' => 'lgpd', 'obs' => 'Template de TIA para Recursos Humanos.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template TIA - Marketing', 'controller' => 'LgpdTiaTemplateMarketing', 'controller_url' => 'lgpd-tia-template-marketing', 'directory' => 'lgpd', 'obs' => 'Template de TIA para Marketing.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template TIA - Financeiro', 'controller' => 'LgpdTiaTemplateFinanceiro', 'controller_url' => 'lgpd-tia-template-financeiro', 'directory' => 'lgpd', 'obs' => 'Template de TIA para Financeiro.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Template TIA - TI', 'controller' => 'LgpdTiaTemplateTi', 'controller_url' => 'lgpd-tia-template-ti', 'directory' => 'lgpd', 'obs' => 'Template de TIA para Tecnologia da Informação.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Exportar TIA PDF', 'controller' => 'LgpdTiaExportPdf', 'controller_url' => 'lgpd-tia-export-pdf', 'directory' => 'lgpd', 'obs' => 'Exportação de teste TIA individual para PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Exportar TIA PDF View', 'controller' => 'LgpdTiaExportPdfView', 'controller_url' => 'lgpd-tia-export-pdf-view', 'directory' => 'lgpd', 'obs' => 'Exportação de teste TIA individual para PDF (visualização).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Exportar Lista TIA PDF', 'controller' => 'LgpdTiaExportPdfList', 'controller_url' => 'lgpd-tia-export-pdf-list', 'directory' => 'lgpd', 'obs' => 'Exportação da lista completa de testes TIA para PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - RIPD =====
            ['name'=> 'Listar RIPD', 'controller' => 'LgpdRipd', 'controller_url' => 'lgpd-ripd', 'directory' => 'lgpd', 'obs' => 'Página para listar Relatórios de Impacto à Proteção de Dados (RIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Criar RIPD', 'controller' => 'LgpdRipdCreate', 'controller_url' => 'lgpd-ripd-create', 'directory' => 'lgpd', 'obs' => 'Página para criar Relatório de Impacto à Proteção de Dados (RIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Editar RIPD', 'controller' => 'LgpdRipdEdit', 'controller_url' => 'lgpd-ripd-edit', 'directory' => 'lgpd', 'obs' => 'Página para editar Relatório de Impacto à Proteção de Dados (RIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar RIPD', 'controller' => 'LgpdRipdView', 'controller_url' => 'lgpd-ripd-view', 'directory' => 'lgpd', 'obs' => 'Página para visualizar Relatório de Impacto à Proteção de Dados (RIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Excluir RIPD', 'controller' => 'LgpdRipdDelete', 'controller_url' => 'lgpd-ripd-delete', 'directory' => 'lgpd', 'obs' => 'Página para excluir Relatório de Impacto à Proteção de Dados (RIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Dashboard RIPD', 'controller' => 'LgpdRipdDashboard', 'controller_url' => 'lgpd-ripd-dashboard', 'directory' => 'lgpd', 'obs' => 'Dashboard com estatísticas e métricas dos Relatórios de Impacto à Proteção de Dados (RIPD).', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            
            // ===== GRUPO 31: LGPD - RIPD - EXPORTAÇÃO PDF =====
            ['name'=> 'Exportar RIPD PDF', 'controller' => 'LgpdRipdExportPdf', 'controller_url' => 'lgpd-ripd-export-pdf', 'directory' => 'lgpd', 'obs' => 'Exportação de relatório RIPD individual para PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Exportar Lista RIPD PDF', 'controller' => 'LgpdRipdExportPdfList', 'controller_url' => 'lgpd-ripd-export-pdf-list', 'directory' => 'lgpd', 'obs' => 'Exportação da lista completa de relatórios RIPD para PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
            ['name'=> 'Visualizar RIPD PDF', 'controller' => 'LgpdRipdExportPdfView', 'controller_url' => 'lgpd-ripd-export-pdf-view', 'directory' => 'lgpd', 'obs' => 'Visualização de relatório RIPD em formato PDF.', 'public_page' => 0, 'page_status' => 1, 'adms_packages_page_id' => 1, 'adms_groups_page_id' => 31],
        ];

        // Percorrer o array com dados que devem ser validados antes de cadastrar
        foreach ($pages as $page) {
            // Verificar se o registro já existe no banco de dados
            $existingRecord = $this->query('SELECT id FROM adms_pages WHERE name=:name', ['name' => $page['name']])->fetch();

            // Se o registro não existir, insere os dados na variável $data para em seguida cadastrar na tabela
            if (!$existingRecord) {
                // Criar o array com os dados da página
                $data[] = [
                    'name' => $page['name'],
                    'controller' => $page['controller'],
                    'controller_url' => $page['controller_url'],
                    'directory' => $page['directory'],
                    'obs' => $page['obs'],
                    'public_page' => $page['public_page'],
                    'page_status' => $page['page_status'],
                    'adms_packages_page_id' => $page['adms_packages_page_id'],
                    'adms_groups_page_id' => $page['adms_groups_page_id'],
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s")
                ];
            }
        }

        // Indicar em qual tabela deve salvar
        $adms_pages = $this->table('adms_pages');

        // Inserir os registros na tabela
        $adms_pages->insert($data)->save();
    }
}
